import { createAddress } from "./Address/createAddress.js";
import { getAddress } from "./Address/getAddress.js";
import { addShipmentToBatch } from "./Batch/addShipmentToBatch.js";
import { createBatch } from "./Batch/createBatch.js";
import { getAllBatches } from "./Batch/getAllBatches.js";
import { createParcel } from "./Parcel/createParcel.js";
import { getParcel } from "./Parcel/getParcel.js";
import { buyShipment } from "./Shipment/buyShipment.js";
import { convertLabelFormat } from "./Shipment/convertLabelFormat.js";
import { createShipment } from "./Shipment/createShipment.js";
import { getAllShipments } from "./Shipment/getAllShipments.js";
import { getShipment } from "./Shipment/getShipment.js";
import { getBatch } from "./Batch/getBatch.js";
import { removeShipmentFromBatch } from "./Batch/removeShipmentFromBatch.js";
import { getCarrierMetadata } from "./CarrierMetadata/getCarrierMetadata.js";
import { createCustomsInfo } from "./Customs/createCustomsInfo.js";
import { createCustomsItem } from "./Customs/createCustomsItem.js";
import { getCustomsInfo } from "./Customs/getCustomsInfo.js";
import { getCustomsItem } from "./Customs/getCustomsItem.js";
import { createForm } from "./Form/createForm.js";
import { createInsurance } from "./Insurance/createInsurance.js";
import { getAllInsurances } from "./Insurance/getAllInsurances.js";
import { getInsurance } from "./Insurance/getInsurance.js";
import { refundInsurance } from "./Insurance/refundInsurance.js";
import { buyOrder } from "./Order/buyOrder.js";
import { createOrder } from "./Order/createOrder.js";
import { retrieveOrder } from "./Order/retrieveOrder.js";
import { buyPickup } from "./Pickup/buyPickup.js";
import { cancelPickup } from "./Pickup/cancelPickup.js";
import { createPickup } from "./Pickup/createPickup.js";
import { getAllPickups } from "./Pickup/getAllPickups.js";
import { getPickup } from "./Pickup/getPickup.js";
import { getRate } from "./Rate/getRate.js";
import { regenRate } from "./Rate/regenRates.js";
import { createRefund } from "./Refund/createRefund.js";
import { getAllRefunds } from "./Refund/getAllRefunds.js";
import { getRefund } from "./Refund/getRefund.js";
import { createReport } from "./Report/createReport.js";
import { getAllReports } from "./Report/getAllReports.js";
import { getReport } from "./Report/getReport.js";

//main function, async function to allow for await keyword
const main = async () => {};

main();
